//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AokanaMusicPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AokanaMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BGM01|569048|大きな空の下で|Ookina Sora No Shita De|广阔的天空之下|廣闊的天空之下
        ///BGM02|327555|高まる胸と食欲|Takamaru Mune To Shokuyoku|心情激动、食欲高涨|心情激動、食慾高漲
        ///BGM03|483679|転がる子猫様|Korogaru Koneko-sama|小猫咪打滚|小貓咪打滾
        ///BGM04|539076|殻の中の小鳥|Kara No Naka No Kotori|壳中的小鸟|殼中的小鳥
        ///BGM05|295291|残念無念|Zannen Munen|悔恨|悔恨
        ///BGM06|1100346|夏の夕暮れ|Natsu No Yugure|夏日的夕阳|夏日的夕陽
        ///BGM07|623132|コントレイル|Contrail|航迹|航跡
        ///BGM08|1231828|一進一退|Isshin Ittai|一进一退|一進一退
        ///BGM09|749738|無限軌道|Mugen Kidou|无限轨道|無限軌道
        ///BGM10|402837|気の抜けたラムネ|Ki No Nuketa Ramune|泄了气的弹珠汽水|洩了氣的彈珠汽水
        ///BGM [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string bgmlist {
            get {
                return ResourceManager.GetString("bgmlist", resourceCulture);
            }
        }
    }
}
